name: Inv2Chest
author: FiraAja
main: FiraAja\Inv2Chest\Main
api: 5.0.0
version: 1.0.0
src-namespace-prefix: FiraAja\Inv2Chest

commands:
  unload:
    description: "Puts your stuff in the chest"
    permission: inv2chest.command

permissions:
  inv2chest.command:
    default: op