# This option will send a message if the player does not have inv2chest.command permission
no-permission: "You do not have permission to do that command"

# This option will send a message if the chest is full
chest-full: "The chest is already full"

# This option will send a message if the block is not a chest
not-a-chest: "The block isn't a chest"